### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by yannik1015** [bkogler/goecharger-api-lite#4]
Running `from goecharger import GoeCharger` inside a normal python shell will result in the following error.

```
Python 3.11.4 (main, Jun 22 2023, 19:40:35) [GCC 12.2.1 20220924] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from goecharger import GoeCharger
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/goecharger/goecharger.py", line 11, in <module>
    from goecharger.excpetion import GoeChargerError
ModuleNotFoundError: No module named 'goecharger.excpetion'; 'goecharger' is not a package
```

**Comment by bkogler** [comment]
Thanks for your contribution, fix is release in version 1.5.0
